# Generated by Django 5.2.5 on 2025-08-25 07:27

import Server.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Server', '0002_category_icon_alter_channel_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to=Server.models.Channel_banner_upload_path),
        ),
        migrations.AddField(
            model_name='channel',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=Server.models.Channel_icon_uplpad_path),
        ),
    ]
